### ISSUE TITLE
Setup - final clarifications

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2023-lesson-introcloud#8]
- [x] You could add to GCP that more detailed instructions will follow for the workshop resources
- [x] The red box for Minikube is not very clear, suggest rephrasing it to
    _To enable Kubernetes on WSL2, you have two options: activating Kubernetes in Docker Desktop or installing Minikube following the Linux option on WSL2 Ubuntu. It’s important to note that the Windows instructions for the Minikube installation guide users to PowerShell, but running the CMSSW container there will cause issues. Therefore, it is necessary to execute those commands within the Ubuntu shell._
  - has someone tested the Kubernetes option of Docker Desktop? Does it start automatically? How does one connect to the cluster?

**Comment by xaviertintin** [comment]
Yes! I just tested Kubernetes on Docker Desktop, I will create a new issue to indicate how to use this option
